### ISSUE TITLE
Assets not displaying

### ISSUE THREAD

**Issue by schradert** [samueldr/nostatoo#1]
Trying to configure non-Steam game library with Nix, and the first program I am attempting is [chiaki-ng](https://github.com/streetpea/chiaki-ng). The program runs great as expected (`/nix/store/jcyx1sr66ma9i67avlfcsc3vqv7lggai-chiaki-launcher/bin/chiaki-launcher` works), but the assets I have added are not showing up in my interface despite `nostatoo show-non-steam-game` indicating seemingly positive results:

```
(#1) "chiaki-ng"
  Name: "chiaki-ng"
  Steam appid: 1
  Executable: "/nix/store/jcyx1sr66ma9i67avlfcsc3vqv7lggai-chiaki-launcher/bin/chiaki-launcher"
  Start directory: "./"
  Launch options: null
  Desktop file: null

Assets:
  - 1.png: yes
  - 1p.png: yes
  - 1_logo.png: yes
  - 1_hero.png: yes

Extra data:
```

The images are valid, and I ran the following commands to reach this state:

```bash
/nix/store/0hwi8h4xmhng0i5nfkc1pry9hrjgf79r-nostatoo-WIP/bin/nostatoo import-non-steam-games /nix/store/yv17yp2if19nnyjhpw3mshf12x0k2jlk-non-steam-games.json
/nix/store/0hwi8h4xmhng0i5nfkc1pry9hrjgf79r-nostatoo-WIP/bin/nostatoo add-asset 1 hero /nix/store/lyxp6bbvi55gwaz7faax5yhjk04y4cyz-chiaki-ng-images/steam_hero.png
/nix/store/0hwi8h4xmhng0i5nfkc1pry9hrjgf79r-nostatoo-WIP/bin/nostatoo add-asset 1 horizontal_capsule /nix/store/lyxp6bbvi55gwaz7faax5yhjk04y4cyz-chiaki-ng-images/steam_landscape.png
/nix/store/0hwi8h4xmhng0i5nfkc1pry9hrjgf79r-nostatoo-WIP/bin/nostatoo add-asset 1 logo /nix/store/lyxp6bbvi55gwaz7faax5yhjk04y4cyz-chiaki-ng-images/steam_logo.png
/nix/store/0hwi8h4xmhng0i5nfkc1pry9hrjgf79r-nostatoo-WIP/bin/nostatoo add-asset 1 vertical_capsule /nix/store/lyxp6bbvi55gwaz7faax5yhjk04y4cyz-chiaki-ng-images/steam_portrait.png
```

`/nix/store/yv17yp2if19nnyjhpw3mshf12x0k2jlk-non-steam-games.json`:

```json
{
  "shortcuts": {
    "1": {
      "Exe": "/nix/store/jcyx1sr66ma9i67avlfcsc3vqv7lggai-chiaki-launcher/bin/chiaki-launcher",
      "StartDir": "./",
      "appid": 1,
      "appname": "chiaki-ng"
    }
  }
}
```

I also tried restarting steam and restarting device, which didn't help at all. All the files I expect to exist as created by `nostatoo` exist.

Any ideas?

**Comment by samueldr** [comment]
:thinking: took me a moment to see what you were doing here.

I had to use `1` as `AppID` to get the same results. With `1` assets won't work...


... to the logs!

```
~ $ ( tail -F ~/.local/share/Steam/logs/* & journalctl --user --follow ) | grep -i shortcut
...
[2024-10-17 03:18:59] sanitize shortcut app id "env": replacing 1 with 2680746172, reason: k_unLocalAppIDFlag not set
```

I'm *guesstimating* that there is a lower bound for valid AppIDs...

... and I now have it on good authority [redacted] that AppID must be at least `0x80001388` to be valid for a user shortcut.

* * *

So, for this issue #1, the solution is to not use the number 1 as an AppID. Start instead at the very memorable 2147488648.

To fix this issue I will

 - Add a check and error condition on import with bogus AppID
 - Add a warning when consuming a vdf with bogus AppID
 - Properly start from the lower bound when making-up an AppID

I believe I didn't hit the issue since I didn't care about the AppID, and steam eventually "fixed" those for me.

**Comment by schradert** [comment]
Amazing, worked like a charm! I thought it might be weird that I set it so low, but everything besides assets worked still, so I thought it might be something else. I should've confirmed in the logs, but didn't really know where to look. At least now we know a little more about how it works! Where did you get `0x80001388` (`2147488648`) from though? It's slightly larger than the maximum for a signed 32-bit integer (not exact), and I'm guessing on purpose if steam games are maybe given AppIDs lower than that limit.

**Comment by samueldr** [comment]
> At least now we know a little more about how it works! Where did you get `0x80001388` (`2147488648`) from though?

Looking extra closely at steam and its implementation. (Reversed it a bit, as a treat.)

> It's slightly larger than the maximum for a signed 32-bit integer (not exact), and I'm guessing on purpose if steam games are maybe given AppIDs lower than that limit.

I don't know how AppID attribution works, but it seems (from the logs, and hints elsewhere) that some patterns or ranges have special meanings.

This is my headcanon about how they got this number, which I **just now** guessed at:

```
irb(main):002> 0x1388
=> 5000
irb(main):005> (5000 | (1 << 31)).to_s(16)
=> "80001388"
```

> **side-note**: when *looking intently* at stuff, looking at the different bases can help... and sometimes the bases are unexpectedly mixed-up!!

When I'd looked yesterday, there were no hints about the 5000, or even some form of bit pattern AFAICT. Optimized out I guess. So I suppose that the rule is "for the upper half of unsigned 32 bit ints", the first 5000 are reserved. Though maybe it's that *for any range* the first 5000 are reserved, and it just happens to also match for non-steam games.

In the end, it makes sense that user-made AppIDs have a given range: a lot of stuff works out of AppIDs in steam, like launching apps. It makes it impossible to "hijack" a steam-provided AppID I would presume.

**Comment by samueldr** [comment]
The latest push prevents importing with bad AppIDs.

 - https://github.com/samueldr/nostatoo/commit/cbfab24d0c41081cb0bd339e8e2d74c390972829

And uses the proper lower bound for IDs.

 - https://github.com/samueldr/nostatoo/commit/0a1813b6d4ed9e9cfc3efb4c1d3d8dd2476121cf

Note that using a random number is how it's implemented downstream. We *could* pick the lowest available AppID from a given range, especially now that we know the lower bound... But at the same time it's not like it would be of any use.
